/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Controllers.LoginController;
import Controllers.NewEmployee;
import Controllers.NewUsers;
import Pojo.Employee;
import Pojo.Users;
import Utils.GlobalVars;
import Utils.Hash;
import Utils.Language;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Evander R
 */
public class FrameLogin extends javax.swing.JFrame {

    LoginController logController = new LoginController();
    NewUsers newUser = new NewUsers();
    Hash h = new Hash();
    NewEmployee newEmployee = new NewEmployee();

    /**
     * Creates new form NewJFrame
     */
    public FrameLogin() {
        initComponents();
        setLanguage();
        this.setResizable(false);
    }

    public void setLanguage() {
        try {
            Language l = new Language();
            this.jLabelUsuario.setText(l.getLabelUsuario());
            this.jLabelContraseña.setText(l.getLabelContraseña());
            this.jCBMostrar.setText(l.getCBMostrar());
            this.jBotonEntrar.setText(l.getBotonEntrar());
        } catch (IOException ex) {
            Logger.getLogger(FrameLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        TextUser = new javax.swing.JTextField();
        jBotonEntrar = new javax.swing.JButton();
        TextPass = new javax.swing.JPasswordField();
        jCBMostrar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabelUsuario.setText("Usuario: ");

        jLabelContraseña.setText("Contraseña: ");

        jBotonEntrar.setBackground(new java.awt.Color(255, 255, 255));
        jBotonEntrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBotonEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon32x32/Login_37128.png"))); // NOI18N
        jBotonEntrar.setText("Entrar");
        jBotonEntrar.setToolTipText("");
        jBotonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonEntrarActionPerformed(evt);
            }
        });

        jCBMostrar.setText("Mostrar");
        jCBMostrar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBMostrarItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsuario)
                    .addComponent(jLabelContraseña))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextUser)
                            .addComponent(TextPass, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBMostrar))
                    .addComponent(jBotonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario)
                    .addComponent(TextUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContraseña)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextPass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCBMostrar)))
                .addGap(18, 18, 18)
                .addComponent(jBotonEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonEntrarActionPerformed
        if (this.TextUser.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite el usuario", "Atención", JOptionPane.ERROR_MESSAGE);
        } else if (this.TextPass.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite la contraseña", "Atención", JOptionPane.ERROR_MESSAGE);
        } else {
            if (logController.access(this.TextUser.getText(), this.TextPass.getText())) {
                setGlobalVars();
                PrincipalBackyard pb = new PrincipalBackyard();
                pb.show();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Credenciales incorrectas", "Atención", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBotonEntrarActionPerformed

    private void jCBMostrarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBMostrarItemStateChanged
        if ((evt.getStateChange() == 1) ? true : false) {
            this.TextPass.setEchoChar((char) 0); //password = JPasswordField
        } else {

            this.TextPass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCBMostrarItemStateChanged

    public void setGlobalVars() {
        Employee e = newEmployee.findEmployeeByUser(this.TextUser.getText());
        Users u= newUser.findByUserName(this.TextUser.getText());
        GlobalVars gv= new GlobalVars();
        gv.setUserId(u.getIdUser());
        gv.setUserName(u.getUserName());
        gv.setNameEmployee(e.getFirstName()+" "+e.getSurname());
        gv.setEmployeeId(e.getIdEmployee());
        gv.setTypeEmployee(e.getTypeEmployee());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TextPass;
    private javax.swing.JTextField TextUser;
    private javax.swing.JButton jBotonEntrar;
    private javax.swing.JCheckBox jCBMostrar;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
