package Pojo;
// Generated 22-may-2017 9:26:58 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Bill generated by hbm2java
 */
public class Bill  implements java.io.Serializable {


     private Integer idBill;
     private Integer idReservation;
     private Date departureDate;
     private Long rode;

    public Bill() {
    }

    public Bill(Integer idReservation, Date departureDate, Long rode) {
       this.idReservation = idReservation;
       this.departureDate = departureDate;
       this.rode = rode;
    }
   
    public Integer getIdBill() {
        return this.idBill;
    }
    
    public void setIdBill(Integer idBill) {
        this.idBill = idBill;
    }
    public Integer getIdReservation() {
        return this.idReservation;
    }
    
    public void setIdReservation(Integer idReservation) {
        this.idReservation = idReservation;
    }
    public Date getDepartureDate() {
        return this.departureDate;
    }
    
    public void setDepartureDate(Date departureDate) {
        this.departureDate = departureDate;
    }
    public Long getRode() {
        return this.rode;
    }
    
    public void setRode(Long rode) {
        this.rode = rode;
    }




}


