package Pojo;
// Generated 22-may-2017 9:26:58 by Hibernate Tools 4.3.1



/**
 * Detailreservationroom generated by hbm2java
 */
public class Detailreservationroom  implements java.io.Serializable {


     private Integer idDetail;
     private Reservation reservation;
     private Room room;

    public Detailreservationroom() {
    }

    public Detailreservationroom(Reservation reservation, Room room) {
       this.reservation = reservation;
       this.room = room;
    }
   
    public Integer getIdDetail() {
        return this.idDetail;
    }
    
    public void setIdDetail(Integer idDetail) {
        this.idDetail = idDetail;
    }
    public Reservation getReservation() {
        return this.reservation;
    }
    
    public void setReservation(Reservation reservation) {
        this.reservation = reservation;
    }
    public Room getRoom() {
        return this.room;
    }
    
    public void setRoom(Room room) {
        this.room = room;
    }




}


