package Pojo;
// Generated 22-may-2017 9:26:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer idEmployee;
     private String firstName;
     private String secondName;
     private String surname;
     private String secondSurname;
     private String docIdentity;
     private String phone;
     private String address;
     private Long salary;
     private String email;
     private Integer typeEmployee;
     private Boolean erasedStatus;
     private Set userses = new HashSet(0);

    public Employee() {
    }

    public Employee(int idEmployee, String firstName, String secondName, String surname, String secondSurname, String docIdentity, String phone, String address, Long salary, String email, Integer typeEmployee, Boolean erasedStatus, Set userses) {
       this.idEmployee = idEmployee;
       this.firstName = firstName;
       this.secondName = secondName;
       this.surname = surname;
       this.secondSurname = secondSurname;
       this.docIdentity = docIdentity;
       this.phone = phone;
       this.address = address;
       this.salary = salary;
       this.email = email;
       this.typeEmployee = typeEmployee;
       this.erasedStatus = erasedStatus;
       this.userses = userses;
    }
   
    public Integer getIdEmployee() {
        return this.idEmployee;
    }
    
    public void setIdEmployee(Integer idEmployee) {
        this.idEmployee = idEmployee;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getSecondName() {
        return this.secondName;
    }
    
    public void setSecondName(String secondName) {
        this.secondName = secondName;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getSecondSurname() {
        return this.secondSurname;
    }
    
    public void setSecondSurname(String secondSurname) {
        this.secondSurname = secondSurname;
    }
    public String getDocIdentity() {
        return this.docIdentity;
    }
    
    public void setDocIdentity(String docIdentity) {
        this.docIdentity = docIdentity;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Long getSalary() {
        return this.salary;
    }
    
    public void setSalary(Long salary) {
        this.salary = salary;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getTypeEmployee() {
        return this.typeEmployee;
    }
    
    public void setTypeEmployee(Integer typeEmployee) {
        this.typeEmployee = typeEmployee;
    }
    public Boolean getErasedStatus() {
        return this.erasedStatus;
    }
    
    public void setErasedStatus(Boolean erasedStatus) {
        this.erasedStatus = erasedStatus;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


