package Pojo;
// Generated 22-may-2017 9:26:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer idReservation;
     private Integer IdEmployee;
     private Integer status;
     private Date registrationDate;
     private Date reservationDate;
     private Date dueDate;
     private Long rode;     
     private Set detailreservationrooms = new HashSet(0);
     private Set detailreservationclients = new HashSet(0);
     private Set extrases = new HashSet(0);

    public Reservation() {
    }

    public Reservation(Date registrationDate, Date reservationDate, Long rode, Set detailreservationrooms, Set detailreservationclients, Set extrases) {
       this.registrationDate = registrationDate;
       this.reservationDate = reservationDate;
       this.rode = rode;
       this.detailreservationrooms = detailreservationrooms;
       this.detailreservationclients = detailreservationclients;
       this.extrases = extrases;
    }
   
    public Integer getIdReservation() {
        return this.idReservation;
    }
    
    public void setIdReservation(Integer idReservation) {
        this.idReservation = idReservation;
    }

    public Integer getIdEmployee() {
        return IdEmployee;
    }

    public void setIdEmployee(Integer IdEmployee) {
        this.IdEmployee = IdEmployee;
    }

    public Integer getStatus() {
        return status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }
    public Date getReservationDate() {
        return this.reservationDate;
    }
    
    public void setReservationDate(Date reservationDate) {
        this.reservationDate = reservationDate;
    }

    public Date getDueDate() {
        return dueDate;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    
    public Long getRode() {
        return this.rode;
    }
    
    public void setRode(Long rode) {
        this.rode = rode;
    }
    public Set getDetailreservationrooms() {
        return this.detailreservationrooms;
    }
    
    public void setDetailreservationrooms(Set detailreservationrooms) {
        this.detailreservationrooms = detailreservationrooms;
    }
    public Set getDetailreservationclients() {
        return this.detailreservationclients;
    }
    
    public void setDetailreservationclients(Set detailreservationclients) {
        this.detailreservationclients = detailreservationclients;
    }
    public Set getExtrases() {
        return this.extrases;
    }
    
    public void setExtrases(Set extrases) {
        this.extrases = extrases;
    }




}


