package Pojo;
// Generated 22-may-2017 9:26:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Room generated by hbm2java
 */
public class Room  implements java.io.Serializable {


     private Integer idRoom;
     private Category category;
     private String name;
     private Integer capacity;
     private Long price;
     private Integer statusRoom;
     private String description;
     private Boolean typeRoom;
     private Boolean erasedStatus;
     private Set detailreservationrooms = new HashSet(0);

    public Room() {
    }

    public Room(Category category, Integer capacity, Long price, Integer statusRoom, String description, Boolean typeRoom, Boolean erasedStatus, Set detailreservationrooms) {
       this.category = category;
       this.capacity = capacity;
       this.price = price;
       this.statusRoom = statusRoom;
       this.description = description;
       this.typeRoom = typeRoom;
       this.erasedStatus = erasedStatus;
       this.detailreservationrooms = detailreservationrooms;
    }
   
    public Integer getIdRoom() {
        return this.idRoom;
    }
    
    public void setIdRoom(Integer idRoom) {
        this.idRoom = idRoom;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    public Integer getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }
    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }
    public Integer getStatusRoom() {
        return this.statusRoom;
    }
    
    public void setStatusRoom(Integer statusRoom) {
        this.statusRoom = statusRoom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Boolean getTypeRoom() {
        return this.typeRoom;
    }
    
    public void setTypeRoom(Boolean typeRoom) {
        this.typeRoom = typeRoom;
    }
    public Boolean getErasedStatus() {
        return this.erasedStatus;
    }
    
    public void setErasedStatus(Boolean erasedStatus) {
        this.erasedStatus = erasedStatus;
    }
    public Set getDetailreservationrooms() {
        return this.detailreservationrooms;
    }
    
    public void setDetailreservationrooms(Set detailreservationrooms) {
        this.detailreservationrooms = detailreservationrooms;
    }




}


